---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "hourly"
  - package-ecosystem: npm
    directory: "/javascript"
    schedule:
      interval: "hourly"
    open-pull-requests-limit: 1
